### ISSUE TITLE
VersionCheck work for non AppStore downloads?

### ISSUE THREAD

**Issue by mattberg** [benbahrenburg/benCoding.iOS.Tools#1]
I'm curious if the versionCheck function has the side effect of checking to see if the app was actually downloaded via the store, or freely via a jailbroken device?

**Comment by benbahrenburg** [comment]
Should technically work as it compares the listing from Apple's servers with the bundle information in the app.

**Comment by benbahrenburg** [comment]
Yes, starting with this commit https://github.com/benbahrenburg/benCoding.iOS.Tools/commit/ff14b84f040e8a284eb1e99a2cec076fb5ab996d
