### ISSUE TITLE
64 bit compatibility and how to test module with app not in app store?

### ISSUE THREAD

**Issue by darkhorse2013** [benbahrenburg/benCoding.iOS.Tools#2]
Great module by the way.

Is the module compatible with 64 bit and is there a way to test the module when it is not released in the app store?

**Comment by darkhorse2013** [comment]
Hi Ben,

Is this compatible with 64 bit?

**Comment by benbahrenburg** [comment]
Yes, starting with this commit https://github.com/benbahrenburg/benCoding.iOS.Tools/commit/ff14b84f040e8a284eb1e99a2cec076fb5ab996d

**Comment by darkhorse2013** [comment]
Hi Ben,

I have downloaded the 0.3 upgrade and I am still getting the error:

couldn't find module:

becoding.ios.tools for architecture:

x86_64

**Comment by geervani** [comment]
Hi Ben,

Same here, using version 0.3. nut still getting "Couldn't find module: bencoding.ios.tools for architecture: x86_64".

Any updates.

Thanks
